@baseUrl = http://localhost:8080/v1

# @name create_movie
POST {{baseUrl}}/movies
Content-Type: application/json

{
  "title": "O Dragão Vermelho",
  "dateRelease": "2002-11-01T14:30:00.000Z",
  "director": "Brett Ratner",
  "genre": "THRILLER",
  "players": [
    {
      "videoURL": "https://www.mmfilmes.me/dragao-vermelho/"
    }
  ]
}

###

# @name update_movie
PATCH {{baseUrl}}/movies/638ea65d-9050-4d53-b27a-485b35d03dea/update
Content-Type: application/json

{
  "cover": "https://upload.wikimedia.org/wikipedia/pt/0/0a/Silence_of_the_lambs.png"
}

###

# @name list_movies
GET {{baseUrl}}/movies
Content-Type: application/json

###

# @name list_movies_by_genre
GET {{baseUrl}}/movies/genre?q=thriller
Content-Type: application/json

{
  "genre": "FICTION"
}

###

# @name get_movie
GET {{baseUrl}}/movies/ff3db394-5c9d-4e82-97c4-82699fc3db62
Content-Type: application/json

###

# @name create_player
POST {{baseUrl}}/players/ccec8600-d539-4689-832c-b60d81566332
Content-Type: application/json

{
  "videoURL": "https://www.mmfilmes.me/o-silencio-dos-inocentes/"
}

###

# @name delete_movie
DELETE {{baseUrl}}/movies/638ea65d-9050-4d53-b27a-485b35d03dea/delete
Content-Type: application/json
